### ISSUE TITLE
Unikey/Telex Vietnamese input method loses composed characters in Virtaal

### ISSUE THREAD

**Issue by vuhung** [translate/virtaal#1496]
Virtaal 0.6.1 doesn't support Unicode

**Comment by Nasdav** [comment]
I try to open a po file that uses UTF-8 encoding and get the following error in Virtaal.exe.log
ERROR:root:MainController.open_file(filename="D:\xampp\htdocs\locale\en_EN\LC_MESSAGES\messages.po", uri="")
Traceback (most recent call last):
  File "virtaal\controllers\maincontroller.pyo", line 208, in open_file
  File "virtaal\controllers\storecontroller.pyo", line 225, in open_file
ValueError: The file contains nothing to translate.
I've change the encoding used and the file opened normally

**Comment by Nasdav** [comment]
I've tried to open a po file that uses a UTF-8 encoding but I get an the following error in virtaal.exe.log 
ERROR:root:MainController.open_file(filename="L:filepath\filename.po", uri="")
Traceback (most recent call last):
  File "virtaal\controllers\maincontroller.pyo", line 208, in open_file
  File "virtaal\controllers\storecontroller.pyo", line 225, in open_file
ValueError: The file contains nothing to translate.

**Comment by friedelwolff** [comment]
Hi @Nasdav. It seems you are posting your support request in a bug about Unikey typing in Vietnamese. I assume you wanted to put that in a separate bug.

You will have to provide substantially more information in the new bug report, though. Please provide the file, and explain exactly where and how you "turned the file's encoding". Please be very specific.

**Comment by dwaynebailey** [comment]
The original report here (Unikey/Telex input interacting badly with Virtaal on Windows) is tied to old GTK2's input-method handling, which has been fully replaced by GTK3's own IM context system in the Python 3 port - worth confirming whether this still reproduces at all on v1.0.0-beta1.

Separately, the later comment about `ValueError: The file contains nothing to translate` opening a UTF-8 .po file is a different, underspecified report that got dropped into this thread by mistake (as already noted above) - that would need its own issue with the actual file and exact steps to investigate, not enough here to act on.

Leaving open pending confirmation on the original Unikey behaviour.

**Comment by dwaynebailey** [comment]
Retitled to reflect the actual report (the original title was just "doesn't support Unicode").

This is tied to old GTK2's input-method handling, fully replaced by GTK3's own IM context system in the Python 3 port. Given the age and that we have no way to test Unikey/Telex ourselves, closing - please reopen (or file fresh) if this still reproduces on v1.0.0-beta1 or later.

On the hijacked comment (UTF-8 .po failing to open with "contains nothing to translate"): tried reproducing with a UTF-8 BOM and with a mismatched declared/actual encoding against current translate-toolkit - neither reproduces (the BOM case parses fine now; the mismatch raises a different, unrelated UnicodeDecodeError). No file was ever attached, so this is as far as we can take it - the earlier comment asking for the actual file and exact steps stands as the way forward if that reporter returns.
