### ISSUE TITLE
Opening a file from a Novell network share fails

### ISSUE THREAD

**Issue by transl8bzimport** [translate/virtaal#1982]
_Version: 0.7.0_

_Originally posted by Pierre BUFFIN:_

Msg when open any files, in a Novell environmeent 
ERROR:root:MainController.open_file(filename="G:\vertaling\VirTaal\BIRB_MAIN_nl-be_fr-be.xlf", uri="")
Traceback (most recent call last):
  File "virtaal\controllers\maincontroller.pyo", line 205, in open_file
  File "virtaal\controllers\storecontroller.pyo", line 220, in open_file
  File "virtaal\models\storemodel.pyo", line 61, in **init**
  File "virtaal\models\storemodel.pyo", line 147, in load_file
  File "virtaal\models\storemodel.pyo", line 171, in update_stats
  File "translate\storage\statsdb.pyo", line 670, in filestatestats
  File "translate\storage\statsdb.pyo", line 144, in decorated_f
  File "translate\storage\statsdb.pyo", line 423, in _getfileid
  File "translate\storage\statsdb.pyo", line 144, in decorated_f
  File "translate\storage\statsdb.pyo", line 468, in _cachestore

**Comment by dwaynebailey** [comment]
This crashed inside translate-toolkit's own old `translate.storage.statsdb` module, which no longer exists in current translate-toolkit (removed some time ago) - Virtaal's stats caching now goes through its own `virtaal/support/statsdb.py` entirely, a different code path. Closing as obsolete; please reopen with a fresh log if a Novell-share open still fails on v1.0.0-beta1.
