### ISSUE TITLE
Replace gtkspell with pygtkspellcheck

### ISSUE THREAD

**Issue by khagaroth** [translate/virtaal#3182]
Gtkspell should be replaced with something that's not absolutely impossible to compile on Windows and isn't available for anything newer than Python 2.5. I would recommend http://koehlma.github.io/projects/pygtkspellcheck.html. It has an optional backwards compatible gtkspell API, so it can work as a drop-in replacement for gtkspell with almost no source modification - even I with almost no Python knowledge managed to get it working. But of course, it would be better to use its native PyGTK API (or PyGObject for the GTK3 branch), but that's work for someone who actually understands Python.

**Comment by PhoneixS** [comment]
This is still a problem. Here is a stack trace:

```
~/Programas$ virtaal
ERROR:root:Failed to load plugin "spellchecker"
No module named gtkspell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtaal/controllers/plugincontroller.py", line 109, in enable_plugin
    self.plugins[name] = plugin_class(name, self.controller)
  File "/usr/lib/python2.7/dist-packages/virtaal/plugins/spellchecker.py", line 69, in __init__
    import gtkspell
ImportError: No module named gtkspell
```

I think that having spellcheckers is something important for a program who deal with translations.

**Comment by PhoneixS** [comment]
```~/Programas$ virtaalERROR:root:Failed to load plugin "spellchecker"No module named gtkspellTraceback (most recent call last):  File "/usr/lib/python2.7/dist-packages/virtaal/controllers/plugincontroller.py", line 109, in enable_plugin    self.plugins[name] = plugin_class(name, self.controller)  File "/usr/lib/python2.7/dist-packages/virtaal/plugins/spellchecker.py", line 69, in __init__    import gtkspellImportError: No module named gtkspell```

**Comment by rffontenelle** [comment]
@PhoneixS Your problem seems to be the same as #3284. Take a look at it, mainly [this comment](https://github.com/translate/virtaal/issues/3284#issuecomment-407049606).

**Comment by dwaynebailey** [comment]
Overtaken by events - current Virtaal uses neither `gtkspell` nor `pygtkspellcheck`. The spellchecker plugin imports `GtkSpell` directly from GObject Introspection (`from gi.repository import GtkSpell`) - the real GTK3-native spell-checking widget, not the old PyGTK wrapper this issue and #3284 were both about. Closing.
