### ISSUE TITLE
Virtaal for Mac 0.7.0 and 0.7.1: "Failed to start TM server"; "Failed to load plugin "localtm"

### ISSUE THREAD

**Issue by jlsigal** [translate/virtaal#3206]
I am running 10.6.8 (Snow Leopard). The two errors listed in the subject are reported in the Console every time I start Virtaal and begin working on an XLIFF file.
I would like to be able to work with both "Current File" and "Local Translation Memory" but of these two "providers" only "Current File" seems to work on the Mac.
I have tried both 0.7.0 and 0.7.1. With 0.7.0., when I enable "Local Translation Memory" on the Configuration window, the setting is not saved when clicking "Close". With 0.7.1., it is difficult to enable the checkbox because the boxes do not line up well and behave erratically, as already reported by another user. I tried deleting all TM providers in the line "disabled_models" of the plugins.ini file under [tm]. A number of the other TM providers do work, but "Local Translation Memory" does not.
Is there a Mac build available with LocalTM functionality?
Please see the Console log below:

``` python-tb
04/08/14 10:03:04   defaults[321]   
The domain/default pair of (za.org.translate.virtaal, AppleLanguages) does not exist
04/08/14 10:03:04   defaults[323]   
The domain/default pair of (za.org.translate.virtaal, AppleCollationOrder) does not exist
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314] ERROR:root:Failed to start TM server
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314] Traceback (most recent call last):
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/virtaal/plugins/tm/models/localtm.py", line 78, in __init__
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     self.tmserver = subprocess.Popen(command)
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/subprocess.py", line 672, in __init__
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     errread, errwrite)
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/subprocess.py", line 1202, in _execute_child
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     raise child_exception
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314] OSError: [Errno 2] No such file or directory
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314] ERROR:root:Failed to load plugin "localtm"
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314] Traceback (most recent call last):
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/virtaal/controllers/plugincontroller.py", line 108, in enable_plugin
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     self.plugins[name] = plugin_class(name, self.controller)
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/virtaal/plugins/tm/models/localtm.py", line 78, in __init__
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     self.tmserver = subprocess.Popen(command)
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/subprocess.py", line 672, in __init__
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     errread, errwrite)
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]   File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/subprocess.py", line 1202, in _execute_child
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314]     raise child_exception
04/08/14 10:03:07   [0x0-0x27027].za.org.translate.virtaal[314] OSError: [Errno 2] No such file or directory
```

Best regards,
Joshua L. Sigal

**Comment by YogieAnamCara** [comment]
Same here on OS X 10.10.3 I'm getting with Virtual 0.7.1 this messages only when starting:

12.05.15 17:35:55,451 defaults[3150]: 
The domain/default pair of (za.org.translate.virtaal, AppleLanguages) does not exist
12.05.15 17:35:55,523 defaults[3152]: 
The domain/default pair of (za.org.translate.virtaal, AppleCollationOrder) does not exist
12.05.15 17:36:05,818 com.apple.xpc.launchd[1]: (za.org.translate.virtaal.130104[3145]) Service exited with abnormal code: 139

then Virtaal closes down.

**Comment by dwaynebailey** [comment]
This is from the old py2app-based macOS build (Python 2.7, `subprocess.Popen` failing to find the bundled tmserver command) - macOS packaging has since been completely rebuilt on PyInstaller, with a different, tested launch mechanism for the local TM server subprocess. Please try [v1.0.0-beta1](https://github.com/translate/virtaal/releases/tag/v1.0.0-beta1) - closing, but reopen with a fresh log if Local Translation Memory still fails to start there.
