### ISSUE TITLE
Can't open file if folde name have letters like "æ"

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3215]
I wanted to report a bug but http://bugs.locamotion.org/ says "Bad Request (400)".

The bug is that i cant open a file in Virtaal if the file is placed in a foldes called for example "oversættelser" with the "æ" letter Virtaal 0.7.1 are not able to open the file.
Virtaal shows a dialog with something like... could not open file... this file does not exists.

If i change "oversættelser" to something without "æ" like "oversettelser", Virtall 0.7.1 are able to open the file.

Using Windows 7.

**Comment by jleclanche** [comment]
bugs.locamotion.org bugzilla has been closed in favour of github, this is the correct place to report bugs.

**Comment by scootergrisen** [comment]
Maybe that site should say it have changed.
On https://github.com/translate/virtaal#reporting-bugs it says to use the Help menu to report bugs.

**Comment by jleclanche** [comment]
Noted, thanks.

**Comment by scootergrisen** [comment]
Only seems i can't open the file from a folder called something like "æ" if i try to drag and drop it into the Virtaal window.

If i try to drag and drop it i get this.
![error](https://user-images.githubusercontent.com/1836590/103445710-2a09bd80-4c78-11eb-86bf-c9daedc76113.jpg)

And when i close the Virtaal window i get a dialog telling me about something was added to the log which is this.
> ERROR:root:MainController.open_file(filename="C:/æ/test.po", uri="")
> Traceback (most recent call last):
>   File "virtaal\controllers\maincontroller.pyo", line 208, in open_file
>   File "virtaal\controllers\storecontroller.pyo", line 220, in open_file
>   File "virtaal\models\storemodel.pyo", line 61, in __init__
>   File "virtaal\models\storemodel.pyo", line 133, in load_file
> IOError: Filen findes ikke.

I can open the file from Windows explorer or open it with open from inside the Virtaal window.
But if i do so the file is not added to the recent files list in Virtaal.

**Comment by dwaynebailey** [comment]
The remaining failure here (drag-and-drop specifically, since Open/Explorer both already work per the thread) looks like the same class of bug just fixed in #3488: GTK's Windows drag-and-drop backend can percent-encode non-ASCII path characters using the system codepage instead of UTF-8, and the old code had no fallback for that mismatch - it would silently fail to resolve the path rather than open the file, matching "æ" specifically failing here. That fix has since shipped. Could you confirm whether dragging a file from an "æ"-named folder now works on v1.0.0-beta1? Leaving open pending that.

**Comment by dwaynebailey** [comment]
Confirmed fixed - drag-and-drop from a non-ASCII-named folder (`Z:\virtaal\devsupport\testfiles\æ\checks æ.po`) opens cleanly on Windows 11 with v1.0.0-beta1 (616c60e).
