### ISSUE TITLE
Unable to open QT (.ts) file with "vanished" translations

### ISSUE THREAD

**Issue by gunchleoc** [translate/virtaal#3263]
The following entry in a QT `.ts` file is keeping Virtaal from opening the file:
```
    <message>
        <source>OK</source>
        <translation type="vanished">Ceart ma-thà</translation>
    </message>
```
The string should be loaded into the TM, but ignored in the UI.
![qt-vanished](https://cloud.githubusercontent.com/assets/4095570/26643601/bc404a56-4629-11e7-8c33-feb18591c305.PNG)

[qtbase_gd.zip](https://github.com/translate/virtaal/files/1042300/qtbase_gd.zip)

**Comment by scootergrisen** [comment]
With Virtaal 0.7.1 i get this in openSUSE:

```
/usr/lib64/python2.7/site-packages/gobject/__init__.py:115: Warning: attempting to add an interface (GtkCellEditable) to class (UnitView) after class_init
  type_register(cls, namespace.get('__gtype_name__'))
ERROR:root:MainController.open_file(filename="qtbase_gd.ts", uri="")
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtaal/controllers/maincontroller.py", line 208, in open_file
    self.mode_controller.refresh_mode()
  File "/usr/lib/python2.7/site-packages/virtaal/controllers/storecontroller.py", line 220, in open_file
    
  File "/usr/lib/python2.7/site-packages/virtaal/models/storemodel.py", line 61, in __init__
    
  File "/usr/lib/python2.7/site-packages/virtaal/models/storemodel.py", line 147, in load_file
    #self._correct_header(self._trans_store)
  File "/usr/lib/python2.7/site-packages/virtaal/models/storemodel.py", line 171, in update_stats
    self._valid_units = stats['total']
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 693, in filestatestats
    fileid = self._getfileid(filename, store=store)
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 150, in decorated_f
    result = f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 433, in _getfileid
    return self._cachestore(store, realpath, mod_info)
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 150, in decorated_f
    result = f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 489, in _cachestore
    self._cacheunitstats(store.units, fileid)
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 150, in decorated_f
    result = f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/translate/storage/statsdb.py", line 461, in _cacheunitstats
    unit.get_state_id()))
  File "/usr/lib/python2.7/site-packages/translate/storage/base.py", line 466, in get_state_id
    n = self.get_state_n()
  File "/usr/lib/python2.7/site-packages/translate/storage/ts2.py", line 353, in get_state_n
    return self.statemap[type]
KeyError: 'vanished'

```

**Comment by dwaynebailey** [comment]
Confirmed fixed. Tested against current translate-toolkit with a .ts file containing a `type="vanished"` message: it loads without error, and the vanished translation is correctly excluded from the units shown in the UI (only the non-vanished message appears).
