### ISSUE TITLE
Virtaal on openSUSE not working correctly

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3265]
I tried installing Virtaal 0.7.1 on openSUSE Thumbleweed with YaST but when i open a po file and select i string i get the following error in the console and the translation area is blank so i can't really use Virtaal.
```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtaal/views/widgets/storecellrenderer.py", line 192, in do_start_editing
    if not getattr(self, '_editor_modified_id', None):
TypeError: <UnitView object at 0x7f75305ce780 (UnitView at 0x555f234330a0)>: unknown signal name: editing-done
/usr/lib/python2.7/site-packages/virtaal/plugins/tm/tmcontroller.py:194: Warning: Source ID 1944 was not found when attempting to remove it
  self._delay_id = gobject.timeout_add(self.QUERY_DELAY, start_query)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtaal/views/widgets/storecellrenderer.py", line 192, in do_start_editing
    if not getattr(self, '_editor_modified_id', None):
TypeError: <UnitView object at 0x7f75305ce780 (UnitView at 0x555f234330a0)>: unknown signal name: editing-done
```

**Comment by friedelwolff** [comment]
Hi @scootergrisen. It reminds me of a matter that we saw several years ago that was because of a bug in pygobject. I reported it here:
https://bugzilla.gnome.org/show_bug.cgi?id=705662
This has mostly been fixed in most Linux distribution, but not yet as part of an official release of pygobject (last time I checked). Maybe you can check to see exactly what is packaged as pygobject on openSUSE - most distributions ship 2.28.6 with additional patches from gnome git, and this seems to solve the problem.

I'm not 100% sure this is the reason for your error, but this would be where I start looking.

**Comment by friedelwolff** [comment]
Hi @scootergrisen. It reminds me of a matter that we saw several years ago that was because of a bug in pygobject. I reported it here:
https://bugzilla.gnome.org/show_bug.cgi?id=705662
This has mostly been fixed in most Linux distribution, but not yet as part of an official release of pygobject (last time I checked). Maybe you can check to see exactly what is packaged as pygobject on openSUSE - most distributions ship 2.28.6 with additional patches from gnome git, and this seems to solve the problem.

I'm not 100% sure this is the reason for your error, but this would be where I start looking.

**Comment by scootergrisen** [comment]
Do you mean pyobject without g?
I got:
python-gobject2 (2.28.6-27.3)
python2-gobject (3.24.1-2.1)
python3-gobject (3.24.1-2.1)

**Comment by friedelwolff** [comment]
Sorry, that was a typo.  python-gobject2 (2.28.6-27.3) is the right one.

**Comment by elchevive** [comment]
Hi,

openSUSE has 2 patches applied only:

**Comment by elchevive** [comment]
Hi,

I tried on Leap 42.3 and got the same:

```
osboxes@linux-9utt:~> virtaal
/usr/lib/python2.7/site-packages/virtaal/views/mainview.py:562: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  from gobject import threads_init
/usr/lib64/python2.7/site-packages/gobject/__init__.py:115: Warning: attempting to add an interface (GtkCellEditable) to class (UnitView) after class_init
  type_register(cls, namespace.get('__gtype_name__'))
/usr/lib64/python2.7/site-packages/gobject/__init__.py:115: Warning: attempting to add an interface (GtkCellEditable) to class (CellWidget) after class_init
  type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtaal/views/widgets/storecellrenderer.py", line 192, in do_start_editing
    if not getattr(self, '_editor_modified_id', None):
TypeError: <UnitView object at 0x7f5df806de10 (UnitView at 0x185c5c0)>: unknown signal name: editing-done

** (virtaal:2804): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
borders don't fit within the image
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtaal/views/widgets/storecellrenderer.py", line 192, in do_start_editing
    if not getattr(self, '_editor_modified_id', None):
TypeError: <UnitView object at 0x7f5df806de10 (UnitView at 0x185c5c0)>: unknown signal name: editing-done
/usr/lib/python2.7/site-packages/virtaal/plugins/tm/tmcontroller.py:194: Warning: Source ID 147 was not found when attempting to remove it
  self._delay_id = gobject.timeout_add(self.QUERY_DELAY, start_query)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtaal/views/widgets/storecellrenderer.py", line 192, in do_start_editing
    if not getattr(self, '_editor_modified_id', None):
TypeError: <UnitView object at 0x7f5df806de10 (UnitView at 0x185c5c0)>: unknown signal name: editing-done
osboxes@linux-9utt:~>
```

**Comment by dwaynebailey** [comment]
Checked current code: UnitView already implements Gtk.CellEditable (which defines the "editing-done" interface signal) and overrides do_editing_done() - this looks like a PyGTK2/GTK2-era interface-signal-registration quirk. This exact code path (storecellrenderer.py's do_start_editing) has been exercised constantly via live testing this session (every file-open/unit-edit) with zero occurrence of this error. Same root issue as the Launchpad-linked #2713 - closing both.
