### ISSUE TITLE
Can't open Virtaal or locate error logfile

### ISSUE THREAD

**Issue by sarahhorrocks** [translate/virtaal#3270]
I get the following error when I try and open Virtaal:

Errors occurred
See logfile C:\Program Files (x86)\Virtaal\virtaal.exe.log for details.

This logfile doesn't seem to exist. Can anyone help?

Thanks in advance.

**Comment by Ricky-Tigg** [comment]
**OS**: Linux – Fedora 28 Desktop
**Component**: virtaal.noarch 0.7.1-13.fc28 @fedora 

**Description**: Attempt to launch application fails.
Step – Install component: '`dnf install -y virtaal`'

`$ virtaal`
`Traceback (most recent call last):`
`  File "/usr/bin/virtaal", line 23, in <module>`
`    from virtaal.common import pan_app`
`  File "/usr/lib/python2.7/site-packages/virtaal/common/__init__.py", line 21, in <module>`
`    import pan_app`
`  File "/usr/lib/python2.7/site-packages/virtaal/common/pan_app.py", line 27, in <module>`
`    from translate.misc import file_discovery`
`ImportError: No module named translate.misc`

**Comment by mbeijen** [comment]
I also found I have @sarahhorrocks problem on Windows 10.

**Comment by cooljeanius** [comment]
hey @knyghtmare is this the same issue that you see?

**Comment by DziarskiDesign** [comment]
I have the same problem as @sarahhorrocks on Windows 11.

**Comment by dwaynebailey** [comment]
Root cause: that dialog and its log path come from py2exe's own error handler (the packaging tool Virtaal 0.7.1 used) - it defaults to writing next to the installed `.exe`, i.e. inside `Program Files`, which a normal non-admin user typically can't write to. So the log the dialog promises often never actually gets created - not a wrong message exactly, but a hardcoded default that assumes install-directory write access most users don't have.

The current build no longer uses py2exe at all (fully replaced by PyInstaller), and our logging now deliberately writes to a per-user, always-writable location (`%APPDATA%\Virtaal\`) specifically to avoid this. Please try the new [v1.0.0-beta1](https://github.com/translate/virtaal/releases/tag/v1.0.0-beta1) - closing since this class of failure shouldn't happen there, but reopen if it does.
