### ISSUE TITLE
Virtaal crashes immediately after opening on macOS (El Capitan)

### ISSUE THREAD

**Issue by lisallreiber** [translate/virtaal#3274]
after installing viraal on a mac book pro (2015) with OS X El Capitain version 10.11.6 (15G1611), it opens for about half a second and then closes again leaving a message that it was terminated suddenly.

**Comment by aperechnev** [comment]
I have the same issue.

**Comment by sneetsher** [comment]
This bug should be re-titled, as it is specific to Mac OS.

- I've installed Virtaal-0.7.1-Mac-Beta-2.dmg from sourceforge.
- Virtaal couldn't launch, it crashes silently  .
- Trying to debug, so launched from CLI:

```
$ /Applications/Virtaal.app/Contents/MacOS/runvirtaal.py 
Traceback (most recent call last):
  File "/Applications/Virtaal.app/Contents/MacOS/runvirtaal.py", line 150, in <module>
    from virtaal.main import Virtaal
  File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/virtaal/main.py", line 28, in <module>
    import gobject
  File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/gobject/__init__.py", line 26, in <module>
    from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
  File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/__init__.py", line 22, in <module>
    from glib._glib import *
ImportError: dlopen(/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so, 2): no suitable image found.  Did find:
	/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so: mach-o, but wrong architecture
	/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so: mach-o, but wrong architecture
```

- Check embedded `_glib.so`

```
$ file /Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so
/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so: Mach-O bundle i386
$ uname -a 
Darwin machine1.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
```

**Comment by rffontenelle** [comment]
Maybe related to #3211

**Comment by dwaynebailey** [comment]
Adjusted the title to make this easier to find - let us know if it doesn't capture your report correctly.

**Comment by dwaynebailey** [comment]
Same symptom family as #3317, slightly different cause: El Capitan predates Catalina's 32-bit drop, so this isn't that. The traceback shows the bundled `_glib.so` was a 32-bit-only (i386) Mach-O being loaded by a 64-bit process - a genuine architecture-mismatch bug in that old 0.7.1 `.dmg`'s own packaging, unrelated to which macOS version you're on.

That whole build toolchain (py2, py2app, PyGTK) has since been fully replaced with native x86_64/arm64 PyInstaller builds. Please try [v1.0.0-beta1](https://github.com/translate/virtaal/releases/tag/v1.0.0-beta1) - note it isn't signed/notarized yet, so macOS will warn on first launch (right-click > Open to bypass Gatekeeper). Closing; reopen if it still crashes.
