### ISSUE TITLE
Crashes on Run OSX 10.15.4

### ISSUE THREAD

**Issue by asdiamond** [translate/virtaal#3317]
Running the application from launchpad results in nothing happening on the screen because the application exists with an error.

Running the bundle manually on the command line gives the following error:
`
./Virtaal: line 17: ./../../Contents/MacOS/python: Bad CPU type in executable
`

Running the `runvirtaal.py` script in the bundle directory gives the following python stack trace:

```
Traceback (most recent call last):
  File "runvirtaal.py", line 150, in <module>
    from virtaal.main import Virtaal
  File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/virtaal/main.py", line 28, in <module>
    import gobject
  File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/gobject/__init__.py", line 26, in <module>
    from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
  File "/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/__init__.py", line 22, in <module>
    from glib._glib import *
ImportError: dlopen(/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so, 2): no suitable image found.  Did find:
	/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so: mach-o, but wrong architecture
	/Applications/Virtaal.app/Contents/Resources/lib/python2.7/site-packages/glib/_glib.so: mach-o, but wrong architecture
```

I have a [2017 MacBook "Pro"](https://support.apple.com/kb/SP754?locale=en_US), no touchbar option if it helps.

**Comment by bavarianbytes** [comment]
Same here. Any news on that?

**Comment by dwaynebailey** [comment]
Confirmed from the traceback: `wrong architecture` / `Bad CPU type in executable` means this old build only shipped a 32-bit Python/PyGTK. macOS 10.15 Catalina (what you're running) dropped support for 32-bit binaries entirely, so this old `.app` can never run there or on any newer macOS - unrelated to the specific Mac model.

Virtaal has since been completely rebuilt with modern, native macOS app bundles (arm64 and x86_64, 64-bit only) - see [v1.0.0-beta1](https://github.com/translate/virtaal/releases/tag/v1.0.0-beta1). Please grab that instead of the old release. Note it's an early beta and the app isn't signed/notarized yet, so macOS will warn on first launch (right-click > Open to bypass Gatekeeper).

Closing since this is a known limitation of the old build. Please reopen if the new release still doesn't run for you.
