### ISSUE TITLE
Traceback during translation/scrolling

### ISSUE THREAD

**Issue by friedelwolff** [translate/virtaal#873]
_Version: 0.3.1_

I got this traceback when scrolling, although something else could have triggered it without me noticing.

Traceback (most recent call last):
  File "/home/fwolff/download/translate/src/virtaal/virtaal/views/widgets/storeviewwidgets.py", line 133, in on_get_value
    unit = self._store[rowref]
  File "/home/fwolff/download/translate/src/virtaal/virtaal/models/storemodel.py", line 56, in __getitem__
    return self.get_unit(index)
  File "/home/fwolff/download/translate/src/virtaal/virtaal/models/storemodel.py", line 100, in get_unit
    return self._trans_store.units[self._valid_units[index]]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/fwolff/download/translate/src/virtaal/virtaal/views/widgets/storeviewwidgets.py", line 468, in do_set_property
    setattr(self, pspec.name, value)
  File "/home/fwolff/download/translate/src/virtaal/virtaal/views/widgets/storeviewwidgets.py", line 456, in _set_unit
    if value.isfuzzy():
AttributeError: 'NoneType' object has no attribute 'isfuzzy'

**Comment by friedelwolff** [comment]
I don't think I've seen this again in ages. Closing.
